CREATE SCHEMA ORDERS_DB AUTHORIZATION DBA;

--SET SCHEMA ORDERS_DB;

    drop table customer if exists;
    drop table order_detail if exists;
    drop table orders if exists;
    DROP  TABLE PAYMENT_TYPE IF EXISTS;
    drop table product if exists;
    drop table purchase_order if exists;

-- Setting up sequences
    CREATE SEQUENCE PAYMENT_TYPE_SEQ AS BIGINT START WITH 100 INCREMENT BY 1;
    CREATE SEQUENCE CUSTOMER_SEQ AS BIGINT START WITH 100 INCREMENT BY 1;
    CREATE SEQUENCE ORDER_DETAIL_SEQ AS BIGINT START WITH 100 INCREMENT BY 1;
    CREATE SEQUENCE ORDERS_SEQ AS BIGINT START WITH 100 INCREMENT BY 1;
    CREATE SEQUENCE PRODUCT_SEQ AS BIGINT START WITH 100 INCREMENT BY 1;
    CREATE SEQUENCE PURCHASE_ORDER_SEQ AS BIGINT START WITH 100 INCREMENT BY 1;

create table customer (
    CUST_ID_NUMBER BIGINT GENERATED BY DEFAULT AS SEQUENCE CUSTOMER_SEQ,
    address varchar(50),
    city varchar(30),
    country varchar(30),
    state varchar(2),
    zip_code varchar(30),
    business_phone varchar(15),
    company varchar(30),
    email_address varchar(50),
    fax_phone varchar(15),
    first_name varchar(30),
    home_phone varchar(15),
    job_title varchar(30),
    last_name varchar(30),
    mobile_phone varchar(15),
    notes varchar(255),
    web_page varchar(100),
    primary key (CUST_ID_NUMBER)
    );

create table order_detail (
    ORD_DETAIL_ID_NUMBER BIGINT GENERATED BY DEFAULT AS SEQUENCE ORDER_DETAIL_SEQ,
    VERSION_ID bigint default 0 not null,
    allocation_date date,
    discount integer,
    quantity integer not null,
    status varchar(255) not null,
    unit_price numeric(22,2) not null,
    fk_order_id bigint not null,
    fk_product_id bigint not null,
    fk_purchase_order_id bigint,
    primary key (ORD_DETAIL_ID_NUMBER)
    );

create table orders (
    ORD_ID_NUMBER BIGINT GENERATED BY DEFAULT AS SEQUENCE ORDERS_SEQ,
    notes varchar(255),
    order_date date,
    paid_date date,
    fk_payment_type bigint,
    shipped_date date,
    address varchar(50),
    city varchar(30),
    state varchar(2),
    zip_code varchar(30),
    ship_fee_amount numeric(22,2),
    status varchar(255) not null,
    fk_customer_id bigint not null,
    primary key (ORD_ID_NUMBER)
    );

CREATE TABLE payment_type (
    payment_type_id BIGINT GENERATED BY DEFAULT AS SEQUENCE PAYMENT_TYPE_SEQ,
    payment_type_name VARCHAR(15),
    payment_type_description VARCHAR(50),
    primary key (payment_type_id)
);

create table product (
    PROD_ID_NUMBER BIGINT GENERATED BY DEFAULT AS SEQUENCE PRODUCT_SEQ,
    category_name varchar(30),
    description varchar(100),
    discontinued boolean,
    list_price numeric(22,2) not null,
    minimum_reorder_level integer,
    product_code varchar(30),
    product_name varchar(100),
    per_unit_measure varchar(30),
    reorder_level integer,
    standard_price numeric(22,2) not null,
    target_level integer,
    primary key (PROD_ID_NUMBER)
    );

create table purchase_order (
    PO_ID_NUMBER BIGINT GENERATED BY DEFAULT AS SEQUENCE PURCHASE_ORDER_SEQ,
    approved_date date,
    created_date date not null,
    executed_date date,
    notes varchar(255),
    payment_amount numeric(22,2) not null,
    payment_date date,
    payment_method BIGINT,
    shipping_amount numeric(22,2),
    status varchar(255) NOT NULL,
    submitted_date date,
    tax_amount numeric(22,2),
    fk_payment_type BIGINT,
    primary key (PO_ID_NUMBER)
    );

    alter table order_detail
        add constraint FK_23b309de725a4fb192023089c92 foreign key (fk_order_id) references orders;

    alter table order_detail
        add constraint FK_66282852ca5e47db9145e9da9b3 foreign key (fk_product_id) references product;

    alter table order_detail
        add constraint FK_fafe09b375b24be0ba22671403a foreign key (fk_purchase_order_id) references purchase_order;

    alter table orders
        add constraint FK_111fcaaaed0543a7a4db03f255a foreign key  (fk_customer_id) references customer;
